### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by rjing001** [andrey-git/home-assistant-custom-ui#199]
2021-03-07 08:45:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component customizer
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/customizer/__init__.py", line 118, in async_setup
hass.services.async_register(DOMAIN, SERVICE_SET_ATTRIBUTE,
TypeError: async_register() takes from 4 to 5 positional arguments but 6 were given

**Comment by Mariusthvdb** [comment]
This is now long deprecated. If you want to use custom-ui under modern Lovelace check https://github.com/Mariusthvdb/custom-ui
