### ISSUE TITLE
ImportError: cannot import name 'add_extra_html_url'  after updating to latest

### ISSUE THREAD

**Issue by laurentdinclaux** [andrey-git/home-assistant-custom-ui#37]
Home Assistant 0.52.1
Custom UI 20170805

I get:

```
2017-09-01 17:30:50 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.customizer. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/srv/homeassistant/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/customizer/__init__.py", line 7, in <module>
    from homeassistant.components.frontend import (
ImportError: cannot import name 'add_extra_html_url'
2017-09-01 17:30:51 ERROR (MainThread) [homeassistant.loader] Unable to find component customizer
2017-09-01 17:30:51 ERROR (MainThread) [homeassistant.setup] Setup failed for customizer: Component not found.
```

**Comment by andrey-git** [comment]
Fix submitted. Update `customizer`.

Sorry for the breakage.
