### ISSUE TITLE
Custom UI showing wrong version when using local hosting (and is broken)

### ISSUE THREAD

**Issue by Aephir** [andrey-git/home-assistant-custom-ui#79]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:**  Chrome 63.0.3239.84 (Official Build) (64-bit)

**CustomUI version:**  NA! This is the issue. In the files I have locally it says 20171227, but in the front end "info" it says 20171019

**Home Assistant release (`hass --version`):**  0.60.0

**Problem-relevant `configuration.yaml` entries:**
```yaml
none
```

**Problem-relevant Home Assistant log entries:**
NOT SURE IF RELEVANT, but the error I get when hosting local is:
```
2018-01-05 02:32:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 58, in ban_middleware
    return (yield from handler(request))
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 215, in coro
    res = yield from res
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 215, in coro
    res = yield from res
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 430, in handle
    result = yield from result
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/frontend/__init__.py", line 485, in get
    _is_latest(self.js_option, request)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/frontend/__init__.py", line 583, in _is_latest
    useragent = parse(request.headers.get('User-Agent'))
  File "/srv/homeassistant/lib/python3.6/site-packages/user_agents/parsers.py", line 254, in parse
    return UserAgent(user_agent_string)
  File "/srv/homeassistant/lib/python3.6/site-packages/user_agents/parsers.py", line 135, in __init__
    ua_dict = user_agent_parser.Parse(user_agent_string)
  File "/srv/homeassistant/lib/python3.6/site-packages/ua_parser/user_agent_parser.py", line 222, in Parse
    'user_agent': ParseUserAgent(user_agent_string, **jsParseBits),
  File "/srv/homeassistant/lib/python3.6/site-packages/ua_parser/user_agent_parser.py", line 249, in ParseUserAgent
    family, v1, v2, v3 = uaParser.Parse(user_agent_string)
  File "/srv/homeassistant/lib/python3.6/site-packages/ua_parser/user_agent_parser.py", line 51, in Parse
    match = self.user_agent_re.search(user_agent_string)
TypeError: expected string or bytes-like object
```

**Any errors from browser Javascript console:**
```
frontend-c873dc80aa0057847f22bcf3fff98f57.html:57 paper-drawer-panel is deprecated. Please use app-layout instead!
ready @ frontend-c873dc80aa0057847f22bcf3fff98f57.html:57

[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

Loaded CustomUI 20171019
```

My "info" in the home assistant frontend shows "Custom UI 20171019", even though I have run the update script, and manually checked that both `/home/homeassistant/.homeassistant/www/custom_ui/state-card-custom-ui.html` and `/home/homeassistant/.homeassistant/www/custom_ui/state-card-custom-ui-es5.html` show "VERSION:"20171227". As far as I can tell, I don't have any files anywhere on my computer with "VERSION:"20171019" anywhere in them. Definitely not in the "www/custom_ui" folder.
 
All the individual lights and switches I have set up with custom UI are gone (the group remains, and I can toggle entire groups of light).

This is only an issue when hosting locally, though due to the scare of a few internet outages, I really don't want to use the hosted method.

Thanks for a great project!

**Comment by andrey-git** [comment]
You have an old version cached. Try force-refresh or manually deleted cache in browser

**Comment by Aephir** [comment]
I have force-refreshed with no luck, but clearing cache seems to have fixed it. 

Thanks a lot!

**Comment by mhofman** [comment]
I'm hitting a similar issue. Clearing the cache on all browsers every time there's an update is not an option. On mobile chrome you can only do this by clearing all site data which will delete customized client name and notification registration. Reconfiguring all that every time, is just not practical.

I'm using the custom component to load the "local" version, and it being chrome on Android, it loads the modern es6 version.

**Comment by loxK** [comment]
Please reopen regarding the last comment. Cache needs to be cleared after each update and on mobile it is so tedious to do. Force refresh never helps.
